services:
  server-mysql: 
    image: mysql:8
    container_name: server-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: db
    volumes:
      - mysql-course:/var/lib/mysql
    networks:
      - server-network

  server-phpmyadmin:
    image: phpmyadmin:latest
    container_name: server-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - server-network

  server-redis:
    image: redis:6.0.5-alpine
    command: redis-server --requirepass todovale
    container_name: server-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - server-network

  client-redis:
    image: rediscommander/redis-commander:latest
    container_name: client-redis
    restart: always
    ports:
      - "5500:8081"
    environment:
      - REDIS_HOST=server-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=todovale
    networks:
      - server-network      

networks:
  server-network:
    driver: bridge
    name: server-network      

volumes:
  mysql-course:
    driver: local
    name: mysql-course
