services:
  server-mysql: 
    image: mysql:8
    container_name: server-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: db
    volumes:
      - mysql-course:/var/lib/mysql
    networks:
      - server-network

  server-phpmyadmin:
    image: phpmyadmin:latest
    container_name: server-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
    name: server-network      

volumes:
  mysql-course:
    driver: local
    name: mysql-course
