services:
  server-mysql: 
    image: mysql:8
    container_name: server-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: db
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - server-network

  server-phpmyadmin:
    image: phpmyadmin:latest
    container_name: server-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - server-network

  server-postgres:
    image: postgres:14.17
    container_name: server-postgres
    ports:
      - "5432:5432"
    env_file:
      - ./postgres/config/.env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - server-network      

  server-pgadmin:
    image: dpage/pgadmin4
    container_name: server-pgadmin
    ports:
      - "5050:80"
    env_file:
      - ./postgres/config/.env-pgadmin
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
    name: server-network      

