### Create
post http://localhost:4600/product
Content-Type: application/json

{ 
    "name": "Product 03", 
    "price": 4700, 
    "description": "New Product 03", 
    "stock": 45000 
}

### Update
put http://localhost:4600/product/1
Content-Type: application/json

{ 
    "price": 2000
}

### Delete
delete http://localhost:4600/product/3

### Get All
get http://localhost:4600/product

### Get By Id
get http://localhost:4600/product/3

### Get by page
get http://localhost:4600/product/page?page=1&size=2