### Create
post http://localhost:4600/user
Content-Type: application/json

{ 
    "name": "User name 09", 
    "lastname": "Lastname 09",
    "email": "email09@company.com",
    "password": "password09",
    "sex": "FEMALE"
}

### Update
put http://localhost:4600/user/091bbac8-8eea-4ea9-af73-9de6b9dca021
Content-Type: application/json

{ 
    "name": "Javier"
}

### Delete
delete http://localhost:4600/user/0dca5eac-9031-4140-b789-56ce58e4e6d0

### Get All
get http://localhost:4600/user

### Get By Id
get http://localhost:4600/user/091bbac8-8eea-4ea9-af73-9de6b9dca021

### Get by page
get http://localhost:4600/user/page?page=1&limit=20